### ISSUE TITLE
Nie problem, pytanko

### ISSUE THREAD

**Issue by 7whoami7** [Kruk939/NoPixel#36]
Można edytować kod skryptów które są przez ciebie podpisane?

**Comment by Kruk939** [comment]
Owszem, rób co chcesz, jak chcesz być fair to pozostaw autora pliku, dorzuć siebie w edit i będzie git.
Jeżeli chcesz używać moich nowszych skryptów to masz na innym repo:

https://github.com/Kruk939/Amity-Framework

```sqf
/*
 	Author: XYZ
 	Date: XYZ
 	Edit: XZY
 	
 	Params:
 		0 - Object - XYZ
 		1 - String - XYZ
 	Description: XYZ
 	Return: XYZ
 */
 ```
